WebApplication2/WebApplication2/Controllers/ExternalApiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class ExternalApiController : Controller
    {
        // GET: ExternalApi
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApplication2/WebApplication2/Controllers/SiteInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Services;

namespace WebApplication2.Controllers
{
    public class SiteInfoController : Controller
    {
        // GET: IpInfo
        public async Task<ActionResult> Index()
        {
            var weatherService = new WeatherForecastProvider();
            var res = await weatherService.GetAuthToken();
            return View(res);
        }

        
    }
}

WebApplication2/WebApplication2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – ASP.NET test application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Test Application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li>@Html.ActionLink("Index page", "Index", "Home")</li>
					<li>@Html.ActionLink("External API", "Index", "ExternalApi")</li>
					<li>@Html.ActionLink("Weather", "Index", "SiteInfo")</li>
					<li>@Html.ActionLink("About page", "About", "Home")</li>
					@*<li>@Html.ActionLink("Contacts", "Contact", "Home")</li>*@
				</ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
		<div>
			@*<div class="container">
				<div class="row">*@
					@RenderBody()
				@*</div>
			</div>*@
		</div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>